name: BTC Risk Monitor

on:
  workflow_dispatch:

  schedule:
    - cron: "0 6 * * *"
    - cron: "0 13 * * *"
    - cron: "30 19 * * *"

jobs:

  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run BTC Risk Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python Bot.py
